# Loader metadata
modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

# TFC: Real World
[[mods]]
    modId = "${modId}"
    version = "${modVersion}"
    displayName = "TFC: Real World"
    credits = "Earth-like world generation using real-world maps, filled with original TerraFirmaCraft content"
    authors = "yazloysasha"
    description = '''TFC: Real World generates a believable Earth-like world using real-world maps for continents, mountains, hotspots and climate, fully populated with TerraFirmaCraft's original content and progression.'''

# Dependencies
[[dependencies.${modId}]]
    modId = "tfc"
    type = "required"
    versionRange = "[4.0.0,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.${modId}]]
    modId = "neoforge"
    type = "required"
    versionRange = "${neoForgeVersionRange}"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.${modId}]]
    modId = "minecraft"
    type = "required"
    versionRange = "${minecraftVersionRange}"
    ordering = "AFTER"
    side = "BOTH"

[[mixins]]
    config = "${modId}.mixins.json"
